// models/Document.js
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Document = sequelize.define('Document', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  type: {
    type: DataTypes.ENUM(
      'supplier_order',  // Generated by buyer AM
      'purchase_order',  // Generated by supplier AM
      'contract'         // Signed agreement
    ),
    allowNull: false
  },
  fileUrl: {
    type: DataTypes.STRING,
    allowNull: false
  },
  docusignEnvelopeId: {  // For tracking signing process
    type: DataTypes.STRING,
    allowNull: true
  },
  signedByBuyerAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  signedBySupplierAt: {
    type: DataTypes.DATE,
    allowNull: true
  }
});

Document.associate = (models) => {
  Document.belongsTo(models.Order, {
    foreignKey: 'orderId',
    as: 'order'
  });
  
  Document.belongsTo(models.User, {
    foreignKey: 'generatedById',
    as: 'generatedBy'
  });
  
  Document.belongsTo(models.User, {
    foreignKey: 'signedById',
    as: 'signedBy',
    allowNull: true
  });
};

module.exports = Document;